version: '3'
services:
  app:
    build: .
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg2023
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/  # Mounting the 'postgres_data' volume for persistent storage

volumes:
  postgres_data:
